directory_flask/app/models.py
from app import db

class Task(db.Model):   # ✅ Capital T
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(100), nullable=False)
    status = db.Column(db.String(20), default="Pending")

directory_flask/app/__init__.py
from flask import Flask,redirect,render_template,flash,request
from flask_sqlalchemy import SQLAlchemy
import os


db=SQLAlchemy()

def createapp():
    app=Flask(__name__)

    app.config['SECRET_KEY']='your_sec_key'
    db_path = os.path.join(os.path.abspath(os.path.dirname(__file__)), '..', 'instance', 'todo.db')
    app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///' + db_path
    app.config['SQLALCHEMY_TRACK_MODIFICATIONS']=False

    db.init_app(app)

    with app.app_context():
        db.create_all()

    from app.routes.auth import auth_bp
    from app.routes.tasks import tasks_bp

    app.register_blueprint(auth_bp)
    app.register_blueprint(tasks_bp)

    

    return app

directory_flask/app/routes/auth.py
from flask import Flask,redirect,render_template,flash,request,Blueprint,session,url_for
auth_bp=Blueprint('auth',__name__)
USER_CREDENTIALS={
    "username":"admin",
    "password":"1234"
}
@auth_bp.route('/login',methods=["POST","GET"])
def login():
    if request.method=="POST":
        username=request.form.get("username")
        password=request.form.get("password")
        if username==USER_CREDENTIALS["username"] and password==USER_CREDENTIALS["password"]:
            session['user']=username
            flash("login Successful","success")
        else:
            flash("Invalid Credentials",'Danger')
            return render_template("login.html")
    return render_template("login.html")

@auth_bp.route('/logout')
def logout():
    session.pop('user',None)
    flash("Logged out succesfully",'info')
    return redirect(url_for('auth.login'))

    

directory_flask/app/routes/tasks.py
from flask import Flask, Blueprint, render_template, redirect, url_for, request, flash, session
from app import db
from app.models import Task

tasks_bp = Blueprint('tasks', __name__)

@tasks_bp.route("/")
def view_tasks():
    if "user" not in session:
        return redirect(url_for('auth.login'))

    tasks = Task.query.all()
    return render_template('tasks.html', tasks=tasks)

@tasks_bp.route('/add', methods=["POST"])
def add_task():
    if "user" not in session:
        return redirect(url_for('auth.login'))

    title = request.form.get('title')
    if title:
        new_task = Task(title=title, status="Pending")
        db.session.add(new_task)
        db.session.commit()
        flash("Task added successfully", "success")
    return redirect(url_for('tasks.view_tasks'))

@tasks_bp.route('/toggle/<int:task_id>', methods=["POST"])
def toggle_status(task_id):
    task = Task.query.get(task_id)
    if task:
        if task.status == "Pending":
            task.status = "Working"
        elif task.status == "Working":
            task.status = "Done"
        else:
            task.status = "Pending"
        db.session.commit()
    return redirect(url_for('tasks.view_tasks'))

@tasks_bp.route('/clear', methods=["POST"])
def clear_tasks():
    if "user" not in session:   # ✅ Protect route
        return redirect(url_for('auth.login'))
    Task.query.delete()
    db.session.commit()
    flash("All Tasks Cleared", "success")
    return redirect(url_for('tasks.view_tasks'))




directory_flask/app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}To-Do-App{% endblock %}</title>
    <link rel="stylesheet" href="{{url_for('static',filename='css/style.css')}}">

</head>
<body>
    {% with messages = get_flashed_messages(with_categories=true) %}
  {% if messages %}
    <ul class="flashes">
    {% for category, message in messages %}
      <li class="alert alert-{{category}}">{{ message }}</li>
    {% endfor %}
    </ul>
  {% endif %}
{% endwith %}

    <header>
        <div class="container">
            <h1>To-Do-App</h1>
            <nav>
                <a href="{{url_for('tasks.view_tasks')}}">Home</a>
                {% if 'user'  in session %}
                <a href="{{url_for('auth.logout')}}">Logout</a>
                {%else%}
                <a href="{{url_for('auth.login')}}">Login</a>
                {% endif %}
            </nav>

        </div>
    </header>
    <main class="container">
        {% with messages = get_flashed_messages(with_categories=True) %}
            {% for category ,message in messages%}
            <div class="flash{{category}}">{{message}}</div>
            {% endfor %}
        {% endwith %}
        {% block content %}

        {% endblock  %}
    </main>
    <footer>
        <div class="container">
            <p>&copy;FLASK TO _DO _APP</p>
        </div>

    </footer>
    
</body>
</html>

directory_flask/app/templates/login.html
{% extends "base.html" %}
{% block title %}Login{% endblock %}
{% block content %}
<div class="login_box">
    <h2>login</h2>
    <form method="POST">
        <div class="form-group">
            <label for="username">Username</label>
            <input type="text" name="username" id="username" required>
        </div>
        <div class="form-group">
            <label for="password">Password</label>
            <input type="password" name="password" id="password" required>
        </div>
        <button type="submit" class="btn">Login</button>
    </form>

</div>
{% endblock %}

directory_flask/app/templates/tasks.html
{% extends "base.html" %}
{% block title %}Tasks Page{% endblock %}
{% block content %}
<div class="task-box">
    <h2>Your Tasks</h2>

    <form action="{{ url_for('tasks.add_task')}}" method="post" class="task-form">
        <input type="text" name="title" placeholder="New Task" required>
        <button type="submit" class="btn">Add Task</button>
    </form>

    {% if tasks %}
    <form method="post" action="{{ url_for('tasks.clear_tasks') }}">
        <button type="submit" class="btn btn-clear">Clear Tasks</button>
        
    </form>

    

    <br>
    <table class="task-table">
        <thead>
            <tr>
                <th>#</th>
                <th>Task</th>
                <th>Status</th>
                <th>Change</th>
            </tr>
        </thead>
        <tbody>
            {% for task in tasks %}
            <tr>
                <td>{{ loop.index }}</td>
                <td>{{ task.title }}</td>
                <td>
                    <span class="badge {{ task.status | lower }}">{{ task.status }}</span>
                </td>
                <td>
                    <form action="{{ url_for('tasks.toggle_status', task_id=task.id) }}" method="post">
                        <button class="btn-small" type="submit">Update</button>
                    </form>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% else %}
    <p>You need to add one task</p>
    {% endif %}
</div>
{% endblock %} 


